project:
  type: website
  output-dir: docs

website:
  title: "Cooper Richason"
  site-url: "cooperrichason.com"
  description: "Data Science Blog and Portfolio"
  favicon: favicon.png
  navbar:
    right:
      - text: "Posts"
        href: blog.qmd
      - text: "Notes"
        href: notes.qmd
      - icon: github
        href: https://github.com/cooper-richason
      - icon: twitter
        href: https://x.com/datacooper?s=21
      - icon: linkedin
        href: https://linkedin.com/in/cooperrichason/
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2023, Cooper Richason" 
    right: 
      - icon: github
        href: https://github.com/cooper-richason
      - icon: twitter 
        href: https://x.com/datacooper?s=21
      - icon: rss
        href: index.xml
  twitter-card:
    creator: "@DataCooper"
    card-style: summary
  repo-url: https://github.com/cooper-richason/blog
  repo-actions: [edit, source]
  announcement: 
    icon: cone
    dismissable: true
    content: "**Under Construction**: Currently in the process of upgrading my site. Please excuse the mess!"
    type: primary
    position: below-navbar

format:
  html:
    theme:
      - morph
      - theme.scss